name: Notify Feilong for Packaging

on:
  push:
    branches:
      - master

jobs:
  notify_buildsdk:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Feilong Packaging
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: openmainframeproject/build-feilong
          event-type: obs-package
