# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request_target:
    # Inputs the workflow accepts.
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  foo:
    steps:
      - name: foo
        run: echo "do stuff involving [${{ secrets.TEST_SECRETT }}]"
